@baseUrl = https://localhost:7011/api/news

POST {{baseUrl}}/register-news
Content-Type: application/json

{
    "Title": "About Cloud Computing",
    "Description": "The Cloud Ecosystem",
    "Body": "Cloud computing is the on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user. Large clouds often have functions distributed over multiple locations.",
    "KeywordsCodes":
    [
        "833D09C9-2B53-4406-8808-14828267EAEC"
    ]
}

###

@id = 5
GET {{baseUrl}}/get-news-detail/{{id}}
Content-Type: application/json